.DEFAULT_GOAL := all

all: Memoria CPU FileSystem Kernel Consola

Memoria: 
	 $(MAKE) -C ../Memoria/Default all
CPU: 
	$(MAKE) -C ../CPU/Default all
FileSystem: 
	$(MAKE) -C ../FileSystem/Default all
Kernel: 
	$(MAKE) -C ../Kernel/Default all
Consola:
	$(MAKE) -C ../Consola/Default all
	